version : '2'
services:
  mysql:
    image: mysql:5.6.35
    volumes:
        - ./mysql/db:/var/lib/mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=123456

  service1:
    image: java:8
    volumes:
        - ./java:/opt/app
#    expose:
#        - 8080
    ports:
        - 9081:8080
    links:
        - mysql:mysql
    command: java -jar /opt/app/spring-boot-docker-example-1.0.0.jar

  service2:
    image: java:8
    volumes:
        - ./java:/opt/app
#    expose:
#        - 8080
    ports:
        - 9082:8080
    links:
        - mysql:mysql
    command: java -jar /opt/app/spring-boot-docker-example-1.0.0.jar

  nginx1:
     image: nginx:latest
     volumes:
        - ./nginx/html:/usr/share/nginx/html:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
     #expose:
     #   - 80
     ports:
        - 8088:80
     links:
        - service1:service1
        - service2:service2